version: '3.0'

services:
  consulserver:
    image: progrium/consul:latest
    hostname: consulserver
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
    command: -server -ui-dir /ui -data-dir /tmp/consul --bootstrap
  web1:
    build: .
    command: node app.js
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    depends_on:
      - consulserver
    environment:
      - ID=koa1
      - PORT=3000
  web2:
    build: .
    command: node app.js
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/app
    depends_on:
      - consulserver
    environment:
      - ID=koa2
      - PORT=4000
  web3:
    build: .
    command: node app.js
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/app
    depends_on:
      - consulserver
    environment:
      - ID=koa3
      - PORT=5000